blog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired
from flask_pagedown.fields import PageDownField

class PostForm(FlaskForm):

	title = StringField('Title', validators=[DataRequired()])
	# content = TextAreaField('Content', validators=[DataRequired()])
	# we substituted for MarkDown rather than simple TextAreaField 
	content = PageDownField('You can write here', validators=[DataRequired()])
	submit = SubmitField('post it!')

blog/posts/routes.py
from flask import render_template, url_for, flash,\
				  redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from blog import db
from blog.models import Post
from blog.posts.forms import PostForm


posts = Blueprint('posts', __name__)

@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
	form = PostForm()
	if form.validate_on_submit():
		post = Post(title=form.title.data, author=current_user, content=form.content.data)
		db.session.add(post)
		db.session.commit()
		flash('Now your post is published!', 'success')
		return redirect(url_for('main.home'))
	return render_template('create_post.html', title='New Post',
							form=form, legend='New Post')

# home.html -> def post() -> post.html
@posts.route('/post/<int:post_id>')
def post(post_id):
	post = Post.query.get_or_404(post_id)
	return render_template('post.html', title=post.title, post=post)

@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
# {{ url_for('post', post_id=post.id) }}
# 1. home.html -> def post() -> post.html
# 2. if user's post -> Update & Delete buttons appear
@login_required
def update_post(post_id):
	post = Post.query.get_or_404(post_id)
	if post.author != current_user:
		abort(403)
	form = PostForm()
	if form.validate_on_submit():
		post.title = form.title.data
		post.content = form.content.data
		db.session.commit() # commit new data from form without add() 
							# as data already in the db
		flash('You tweaked the post!', 'primary')
		return redirect(url_for('posts.post', post_id=post.id))
	elif request.method == 'GET': # if we just find ourselves on the page
		form.title.data = post.title
		form.content.data = post.content
	return render_template('create_post.html', title='Update post',
							legend='Update Post' ,form=form)

@posts.route('/post/<int:post_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_post(post_id):
	post = Post.query.get_or_404(post_id)
	if current_user != post.author:
		abort(403)
	db.session.delete(post)
	db.session.commit()
	flash('Now your post is erased!', 'primary')
	return redirect(url_for('main.home'))

blog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from blog import db, bcrypt
from blog.models import User, Post
from blog.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                              RequestResetForm, ResetPasswordForm)
from blog.users.utils import save_pic, send_email, send_confirm_email

users = Blueprint('users', __name__)


'''Blueprint.before_request is called before each request within the blueprint.
If you want to call it before all blueprints, please use before_app_request.'''
@users.before_app_request
def before_request():
	if current_user.is_authenticated:
		current_user.ping()
		if not current_user.confirmed and request.endpoint \
	    and request.blueprint != 'users' and request.endpoint != 'static':
	    # if not confirmed then user can only visit 'users blueprint features'
			return redirect(url_for('users.first_confirm'))

@users.route('/confirm_first')
def first_confirm():
	if current_user.is_anonymous or current_user.confirmed:
		return redirect(url_for('main.home'))
	return render_template('conf.html')

@users.route('/register', methods=['GET', 'POST'])
def register():
	if current_user.is_authenticated: # .attribute comes from UserMixin class
		return redirect(url_for('main.home')) # so as logged user doesn't see those register&login
	form = RegistrationForm()
	if form.validate_on_submit(): # this func() triggers validate_funcs()
		hashed_pass = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		new_user = User(username=form.username.data, email=form.email.data,
						password=hashed_pass, country=form.country.data)
		db.session.add(new_user)
		db.session.commit()

		send_confirm_email(new_user)

		flash(f'Account for {form.username.data} \
				has been created. Verify your account by the link sent to the email', 'success')
		return redirect(url_for('users.login'))
	return render_template('register.html', title='Registration', form=form)

@users.route('/confirm/<token>')
@login_required
# user must be logged but unconfirmed
def confirm(token):
	if current_user.confirmed:
		return redirect(url_for('main.home'))
	if current_user.verify_token(token):
		db.session.commit()
		flash('You have successfully verified your account', 'success')
		return redirect(url_for('users.login'))
	flash('Issue: either link has expired or it is a wrong one')
	return redirect(url_for('users.register'))

@users.route('/confirm')
@login_required
def resend_conf():
	send_confirm_email(current_user)
	flash('A new message was sent to your mail')
	return redirect(url_for('users.login'))

@users.route('/login', methods=['GET', 'POST'])
def login():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first() # check if user in db else None
		if user and bcrypt.check_password_hash(user.password, form.password.data):
			# Once a user has authenticated, you log them in with the login_user function
			login_user(user, remember=form.check.data)
			next_page = request.args.get('next') # either route or None. Look below for expl
			return redirect(next_page) if next_page else redirect(url_for('main.home'))
			# if initially accessed by '/account' => redirects to 'account.html'
			# elif firstly logged by button => redirects to 'home.html'
		flash('Something went wrong. Check your credetentials.', 'danger')
	return render_template('login.html', title='Login', form=form)

@users.route('/logout', methods=['GET', 'POST'])
def logout():
	logout_user()
	flash('You are now logged out')
	return redirect(url_for('main.home'))


@users.route('/account', methods=['GET', 'POST'])
@login_required 
# @.. enables that '/account' not being
# logged results in unathorized error
# But if we provide in __init__: ...view = 'func'
# that '.view' will redirect to it
def account():
	form = UpdateAccountForm()
	if form.validate_on_submit():
		if form.pic.data:
			pic_file = save_pic(form.pic.data)
			current_user.image_file = pic_file
		current_user.username = form.username.data
		current_user.email = form.email.data
		current_user.country = form.country.data
		db.session.commit()
		flash('Your acc now is altered!', 'warning')
		return redirect(url_for('users.account'))
	elif request.method == 'GET': # if we don't send data + if we simply open page
		form.username.data = current_user.username
		form.email.data = current_user.email
		form.country.data = current_user.country
	image_file = url_for('static', filename='pics/' + current_user.image_file)
	return render_template('account.html', title='Account',
							form=form, image_file=image_file)

@users.route('/delete', methods=['GET', 'POST'])
@login_required
def delete_account():
	if request.method == 'POST':
		user = User.query.filter_by(id=current_user.id).first()
		if not user:
			flash('No user with such id found', 'danger')
			return redirect(url_for('main.home'))
		elif current_user != user:
			flash('You cannot delete others account', 'danger')
			return redirect(url_for('main.home'))
		db.session.delete(user)
		db.session.commit()
		flash(f'{user.username} account has been erased!', 'info')
		return redirect(url_for('users.register'))
	return render_template('delete_account.html')

@users.route('/follow/<string:username>')
@login_required
def follow(username):
	user = User.query.filter_by(username=username).first()
	if not user:
		flash('No user with such username', 'danger')
		return redirect('main.home')
	if current_user.is_following(user):
		flash('You are already following this user','info')
		return redirect('main.home')
	current_user.follow(user)
	db.session.commit()
	flash(f'You now follow {username}', 'primary')
	return redirect(url_for('main.home'))

@users.route('/unfollow/<string:username>')
@login_required
def unfollow(username):
	user = User.query.filter_by(username=username).first()
	if not user:
		flash('No user with such username', 'danger')
		return redirect('main.home')
	if not current_user.is_following(user):
		flash('You do not follow this user','info')
		return redirect('main.home')
	current_user.unfollow(user)
	db.session.commit()
	flash(f'You have unfollowed {username}', 'info')
	return redirect(url_for('main.home'))

@users.route('/followers/<string:username>')
def followers(username):
	user = User.query.filter_by(username=username).first()
	if user is None:
		flash('No such user', 'danger')
		return redirect(url_for('users.all_users'))
	page = request.args.get('page', 1, type=int)
	page_2 = user.followers.paginate(page, per_page=5, error_out=False)

	# follows = [{'user': item.follower, 'timestamp': item.timestamp}
	# 		for item in page_2.items]

	return render_template('followers.html', user=user, title='Followers of', pagination=page_2)


	# return render_template('followers.html', user=user, title='Followed of',
	# 						pagination=page_2, follows=follows, endpoint='.followers')

@users.route('/followed_by/<string:username>')
def followed_by(username):
	user = User.query.filter_by(username=username).first()
	if user is None:
		flash('No such user', 'danger')
		return redirect(url_for('users.all_users'))
	page = request.args.get('page', 1, type=int)
	page_2 = user.followed.paginate(page, per_page=5, error_out=False)



	return render_template('followers.html', user=user, title='Followed of', pagination=page_2)

@users.route('/all_users')
@login_required
def all_users():
	page = request.args.get('page', 1, type=int)
	users = User.query.paginate(per_page=5, page=page)
	return render_template('all_users.html', title='List of users', users=users)

# some temp route
@users.route('/all_user/username', methods=['GET', 'POST'])
@login_required
def user_info_2(username):
	user1 = User.query.filter_by(username=username).first()
	form = UpdateAccountForm()
	'''
	if current_user then it can see the form
	if not current_user then only observe
	+ after I've changed
	url_for('users.user_info', user=user.id) 
	rather than user=user aforewriiten stuff started working
	'''
	if form.validate_on_submit():
		if form.pic.data:
			pic_file = save_pic(form.pic.data)
			current_user.image_file = pic_file
		current_user.username = form.username.data
		current_user.email = form.email.data
		current_user.country = form.country.data
		db.session.commit()
		flash('You has altered you account!', 'primary')
		return redirect(url_for('users.account'))
	elif request.method == 'GET': # if we don't send data + if we simply open page
		form.username.data = user1.username
		form.email.data = user1.email
		form.country.data = user1.country
	return render_template('user_info.html', title='User info',
							user=user1, form=form)



@users.route('/all_user/<int:user_id>', methods=['GET', 'POST'])
@login_required
def user_info(user_id):
	user1 = User.query.filter_by(id=user_id).first()
	form = UpdateAccountForm()
	'''
	if current_user then it can see the form
	if not current_user then only observe
	+ after I've changed
	url_for('users.user_info', user=user.id) 
	rather than user=user aforewriiten stuff started working
	'''
	if form.validate_on_submit():
		if form.pic.data:
			pic_file = save_pic(form.pic.data)
			current_user.image_file = pic_file
		current_user.username = form.username.data
		current_user.email = form.email.data
		current_user.country = form.country.data
		db.session.commit()
		flash('You has altered you account!', 'primary')
		return redirect(url_for('users.account'))
	elif request.method == 'GET': # if we don't send data + if we simply open page
		form.username.data = user1.username
		form.email.data = user1.email
		form.country.data = user1.country
	return render_template('user_info.html', title='User info',
							user=user1, form=form)

@users.route('/user/<string:username>')
# 1. 'home.html' <a class="mr-2" href="{{ url_for('user_posts', username=posts.author.username) }}">
def user_posts(username):

blog/templates/account.html
{% extends 'layout.html' %}
{% block content %}
<div class="content-section">
      <div class="media">

        <nav>
            <img class="rounded-circle account-img" src="{{ image_file }}">
        </nav>
        
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %} <br> 
                </div>

                <div class="form-group">

                    {{ form.country.label(class="form-control-label") }} <span><a href="http://maps.google.com/?q={{ current_user.country }}">Click to see on the map!</a></span>
                    {% if form.country.errors %}
                        {{ form.country(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.country.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.country(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.pic.label() }}
                    {{ form.pic(class="form-control-file") }}
                    {% if form.pic.errors %}
                        {% for error in form.pic.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>


{% endblock %}

blog/templates/conf.html
{% extends 'layout.html' %}
{% block content %}
<div class="container warning">
    <div class="row">
		<h1 class="col-md-1"><span class="glyphicon glyphicon-exclamation-sign"></span></h1>
        <h4 class="col-md-10">Warning: Please, confirm your account before using the blog</h4>
	</div>
	<div>
		<ul>
			<p>Lost our email and need to resend it?</p>
			<li>Click here to resend: <a href="{{ url_for('users.resend_conf') }}">link</a></li>
		</ul>
	</div>
</div>
{% endblock content %}

blog/templates/delete_account.html
{% extends 'layout.html' %}
{% block content %}

                <!--start-->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#deleteModal">
  Delete your account
</button>

<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="deleteModalLabel">Are you sure?</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
				<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
				<form action="{{ url_for('users.delete_account', user_id=current_user.id) }}" method="POST">
				<input class="btn btn-danger" type="submit" value="Delete">
				</form>
			</div>
		</div>
	</div>
</div>


                <!--end-->


{% endblock content %}

blog/templates/followers.html
{% extends 'layout.html' %}

{% block title %}
{{ title }} {{ user.username }}
{% endblock title %}

{% block content %}


<table class="table table-hover followers">
    <thead><tr><th>User</th><th>Since</th></tr></thead>
    {% for follow in pagination.items %}
        {% if follow.user != user %}
    <tr>
        <td>
            <a href="{{ url_for('users.user_info_2', username = follow.followers) }}">
                    {{ follow.followers }}
            </a>
        </td>
       
    </tr>
        {% endif %}
    {% endfor %}
</table>

{% endblock content %}

blog/templates/layout.html
<!doctype html>
<html lang="en">
  <head>
    <!-- {{ pagedown.html_head() }} -->

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

   <!-- Bootstrap CSS -->
 
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">


    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">


    {% if title %}
        <title> {{ title }} </title>
    {% else %}
        <title> Blog </title>
    {% endif %}
  </head>

  <body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Welcome!</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('users.delete_account') }}">Delete Account</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          <!--first variant
          {% for message in get_flashed_messages() %}
          <div class='alert alert-warning'>
              <button type="button" class='close' data-dismiss='alert'>&times;</button>
                {{ message }}
          </div>
          {% endfor %}
        -->

          <!--second variant-->
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class='alert alert-{{ category }}'>
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}


          {% block content %}
          {% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Sidebar</h3>
            <p class='text-muted'>Please, use these links
              <ul class="list-group">
                <li class="list-group-item list-group-item-light"><a href="{{ url_for('users.all_users') }}">List of users</a></li>
                <li class="list-group-item list-group-item-light"><a href="{{ url_for('weather.weather_home') }}">Weather</a></li>
                <li class="list-group-item list-group-item-light"><a href="{{ url_for('calendar.see_calen') }}">Calendar</a></li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
     <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  </body>
</html> 

blog/templates/post.html
{% extends 'layout.html' %}
{% block content %}

{{ super() }}
{{ pagedown.include_pagedown() }} 

  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='pics/' + post.author.image_file) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        {% if post.author == current_user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ post.title }}</h2>
      <p class="article-content">
                {% if post.body_html %}
                    {{ post.body_html | safe }}
                {% else %}
                    {{ post.content }}
                {% endif %}
     <!--  {{ post.content }} --></p>
    </div>
  </article>

  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Are you sure?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

blog/templates/results.html
{% extends 'layout.html' %}
{% block content %}

<body>
<div id="weatherResults">
    <h3>Weather in {{ location }}</h3>
    <h2>{{ temp }}° C</h2>
    <h3>{{ weather }}</h3>
    <h4>Feels like: {{ temp_feels }}° C</h4>
</div>
</body>

{% endblock content %}

blog/templates/user_info.html
{% extends 'layout.html' %}
{% block content %}


<div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ url_for('static', filename='pics/' + user.image_file) }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>

      {% if current_user.username == user.username %}
      <!-- if user opens his/her page then it can be modified, otherwise just
      	   observe and and do actions related to following -->

        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %} <br> 
                </div>

                <div class="form-group">

                    {{ form.country.label(class="form-control-label") }} <span><a href="http://maps.google.com/?q={{ current_user.country }}">Click to see on the map!</a></span>
                    {% if form.country.errors %}
                        {{ form.country(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.country.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.country(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.pic.label() }}
                    {{ form.pic(class="form-control-file") }}
                    {% if form.pic.errors %}
                        {% for error in form.pic.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>



        {% else %}
        	<article>
            
                <legend class="border-bottom mb-4">Account Info</legend>
                <div>
                	<ul>
                		{% if not current_user.is_following(user) %}
                			<li><a href="{{ url_for('users.follow', username=user.username) }}" class="btn btn-primary">Follow</a></li>
                		{% else%}
                			<li><a href="{{ url_for('users.unfollow', username=user.username) }}" class="btn btn-primary">Unfollow</a></li>
                		{% endif %}

                		<li>{{ user.country }} <span><a href="http://maps.google.com/?q={{ user.country }}">Click to see on the map!</a></span></li>

                		<a href="{{ url_for('users.followers', username=user.username) }}">Followers: <span class='badge'>{{ user.followers.count() }}</span></a>

                		<a href="{{ url_for('users.followed_by', username=user.username) }}">Following: <span class='badge'>{{ user.followed.count() }}</span></a>



                	</ul>
                </div>
       
        	</article>
        {% endif %}
    </div>
{% endblock content %}

blog/templates/user_posts.html
{% extends 'layout.html' %}
{% block content %}
  <h1 class='mb-3'>Belonged to {{ user.username }} <hr>
                          {{ posts.total }}</h1>
  {% for post in posts.items %} <!-- .items is added as 'posts' is a pagination object-->
    <article class="media content-section">
        <img class='rounded-circle article-img' src="{{ url_for('static', filename='pics/' + post.author.image_file) }}">
        <!--rounded-circle is bootstrap and article-img is in .css-->
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a> 
              <!--to display only username instead of
                  User: qwerty, qwerty@mail.com, 9bc745e670b53437.JPG-->
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content"><!-- {{ post.content }} -->
                {% if post.body_html %}
                    {{ post.body_html | safe }}
                {% else %}
                    {{ post.content }}
                {% endif %}
            </p>
          </div>
        </article>
  {% endfor %}

  {% for page in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page %}
      {% if posts.page == page %}
      <!-- posts.page received from 'routes' -->
      <a class='btn btn-info mb-4' href="{{ url_for('users.user_posts', username=user.username, page=page) }}">{{ page }}</a>
      {% else %}
      <a class='btn btn-outline-info mb-4' href="{{ url_for('users.user_posts', username=user.username, page=page) }}">{{ page }}</a>
     {% endif %} 
    {% else %}
      ...
    {% endif %}
  {% endfor %}
{% endblock content %}